name: Deploy to Huawei Cloud

on:
  push:
    branches:
      - main # 只有当你执行 git push 推送到 main 分支时才会触发同步

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync to Huawei Cloud
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HUAWEI_SSH_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "./" # 搬运当前目录下（即你截图中的所有文件）到服务器
          REMOTE_HOST: ${{ secrets.HUAWEI_SERVER_IP }}
          REMOTE_USER: ${{ secrets.HUAWEI_SSH_USER }}
          TARGET: "/var/www/html" # 华为云 Nginx 默认的网页存放路径
          EXCLUDE: "/.git/, /.github/"